# Generated by Django 5.2.3 on 2026-05-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssource_newsarticle_source_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
