# Generated by Django 5.2.14 on 2026-05-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_options_newsarticle_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-created_at']},
        ),
    ]
