# Generated by Django 5.2.3 on 2026-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='trending_score',
            field=models.IntegerField(default=0),
        ),
    ]
