export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '◉' },

  { id: 'Technology', label: 'Tech', icon: '⚡' },

  { id: 'Politics', label: 'Politics', icon: '🏛' },

  { id: 'Sports', label: 'Sports', icon: '⚽' },

  { id: 'Healthcare', label: 'Health', icon: '🩺' },

  { id: 'General', label: 'General', icon: '🌍' },
]

export const DUMMY_ARTICLES = [
  {
    id: 1,
    title: "OpenAI unveils GPT-5 with unprecedented reasoning capabilities surpassing human benchmarks",
    summary: "The latest model from OpenAI demonstrates remarkable improvements in mathematical reasoning, coding, and multimodal understanding, setting new records across all major AI benchmarks.",
    content: "OpenAI has officially launched GPT-5, its most powerful language model to date...",
    image_url: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    source: "TechCrunch",
    source_url: "https://techcrunch.com",
    published_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    upvotes: 4821,
    user_vote: null,
    category: "technology",
    comment_count: 342,
    read_time: 5,
  },
  {
    id: 2,
    title: "India's Chandrayaan-4 mission successfully lands near lunar south pole, discovers water ice deposits",
    summary: "ISRO's ambitious follow-up mission has achieved what scientists call a 'historic breakthrough', with onboard instruments confirming accessible water ice that could fuel future lunar habitation.",
    content: "In a landmark achievement for Indian space exploration...",
    image_url: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80",
    source: "The Hindu",
    source_url: "https://thehindu.com",
    published_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    upvotes: 9234,
    user_vote: null,
    category: "science",
    comment_count: 891,
    read_time: 7,
  },
  {
    id: 3,
    title: "Markets surge as RBI holds rates steady, signals accommodative stance through 2026",
    summary: "Sensex gains 1,200 points following the Reserve Bank of India's decision to maintain benchmark lending rates, with the central bank governor hinting at potential cuts in Q2.",
    content: "Indian equity markets staged a strong rally on Thursday...",
    image_url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    source: "Economic Times",
    source_url: "https://economictimes.com",
    published_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    upvotes: 2103,
    user_vote: null,
    category: "business",
    comment_count: 187,
    read_time: 4,
  },
  {
    id: 4,
    title: "Elon Musk announces Neuralink has successfully restored full mobility to three paralyzed patients",
    summary: "The brain-computer interface company published peer-reviewed results showing three patients with spinal cord injuries regained full motor control using the N2 implant.",
    content: "Neuralink, the brain-computer interface company founded by Elon Musk...",
    image_url: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80",
    source: "MIT Technology Review",
    source_url: "https://technologyreview.com",
    published_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    upvotes: 7456,
    user_vote: null,
    category: "health",
    comment_count: 623,
    read_time: 8,
  },
  {
    id: 5,
    title: "Premier League: Manchester City clinch historic 7th consecutive title with 4-0 rout of Arsenal",
    summary: "Erling Haaland's hat-trick sealed yet another dominant campaign for Pep Guardiola's side, extending their record for most consecutive top-flight titles in English football history.",
    content: "Manchester City have done it again...",
    image_url: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80",
    source: "BBC Sport",
    source_url: "https://bbc.com/sport",
    published_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    upvotes: 5892,
    user_vote: null,
    category: "sports",
    comment_count: 1203,
    read_time: 3,
  },
  {
    id: 6,
    title: "EU passes landmark AI Accountability Act requiring transparency in all public-facing AI systems",
    summary: "The sweeping legislation mandates that companies disclose when AI is used in hiring, lending, or content moderation decisions, with penalties up to 6% of global revenue for violations.",
    content: "The European Parliament has voted overwhelmingly to pass the AI Accountability Act...",
    image_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    source: "Reuters",
    source_url: "https://reuters.com",
    published_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    upvotes: 3341,
    user_vote: null,
    category: "politics",
    comment_count: 445,
    read_time: 6,
  },
  {
    id: 7,
    title: "Jaipur's Pink City tech corridor attracts ₹12,000 crore in startup investment this quarter",
    summary: "The Rajasthan government's Smart City initiative has transformed Jaipur into India's fastest-growing startup hub outside the traditional metros, with over 400 new ventures registered.",
    content: "Jaipur is experiencing an unprecedented technology boom...",
    image_url: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    source: "Business Standard",
    source_url: "https://business-standard.com",
    published_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    upvotes: 1876,
    user_vote: null,
    category: "business",
    comment_count: 234,
    read_time: 5,
  },
  {
    id: 8,
    title: "Scientists discover room-temperature superconductor that actually works at ambient pressure",
    summary: "A team from Seoul National University has published reproducible results showing a modified lutetium hydride compound exhibiting zero electrical resistance at 22°C and 1 atm.",
    content: "After years of failed claims and retractions...",
    image_url: "https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&q=80",
    source: "Nature",
    source_url: "https://nature.com",
    published_at: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    upvotes: 12043,
    user_vote: null,
    category: "science",
    comment_count: 1876,
    read_time: 9,
  },
]

export const DUMMY_COMMENTS = [
  {
    id: 1,
    user: { username: 'devprakash_rao', avatar: null, karma: 8234 },
    content: "This is absolutely massive. I've been following room-temperature superconductor research for years and the number of failed claims has made everyone understandably skeptical. But Seoul National is a reputable lab and if the results are truly reproducible... we're talking about a paradigm shift in energy transmission, maglev transport, and quantum computing all at once.",
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    upvotes: 2341,
    user_vote: null,
    replies: [
      {
        id: 2,
        user: { username: 'quantumleap99', avatar: null, karma: 3102 },
        content: "Agreed, but let's wait for independent replication first. LK-99 taught us all a painful lesson. I'll be cautiously optimistic but I'm not popping champagne yet.",
        created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
        upvotes: 987,
        user_vote: null,
        replies: [
          {
            id: 3,
            user: { username: 'priya_physics', avatar: null, karma: 5671 },
            content: "The paper mentions replication by two independent groups already — MIT and ETH Zurich both confirmed. That's why Nature fast-tracked it. This is the real deal.",
            created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
            upvotes: 1432,
            user_vote: null,
            replies: [],
          }
        ],
      },
      {
        id: 4,
        user: { username: 'aditya_v', avatar: null, karma: 1200 },
        content: "If this holds up, it's literally the biggest materials science discovery of the century. Energy grid losses alone would be eliminated — that's like 15% of all electricity generated in most countries.",
        created_at: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
        upvotes: 654,
        user_vote: null,
        replies: [],
      }
    ],
  },
  {
    id: 5,
    user: { username: 'saranya_k', avatar: null, karma: 2890 },
    content: "The implications for MRI machines alone would be incredible. Currently they cost ₹10-15 crore partly because of the liquid helium cooling infrastructure. Room temp superconductors would make them affordable for tier-2 city hospitals. This is genuinely life-saving technology if it works.",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    upvotes: 1876,
    user_vote: null,
    replies: [
      {
        id: 6,
        user: { username: 'medtech_mumbai', avatar: null, karma: 4500 },
        content: "Exactly. Healthcare infrastructure in India would be transformed. You're thinking about this exactly right.",
        created_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
        upvotes: 432,
        user_vote: null,
        replies: [],
      }
    ],
  },
  {
    id: 7,
    user: { username: 'skeptic_singh', avatar: null, karma: 670 },
    content: "I'll believe it when I see my electricity bill go down lol. How many times have we heard 'breakthrough' in materials science?",
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    upvotes: 234,
    user_vote: null,
    replies: [],
  },
]

export const TRENDING = DUMMY_ARTICLES.slice().sort((a, b) => b.upvotes - a.upvotes).slice(0, 5)
